name: main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Bump version
        id: bump-version
        uses: "yakovlev-alexey/bump-package-version-action@v1.1.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: "feat!"
          minor-wording: "feat"
          patch-wording: "fix"

      - name: Publish npm
        if: steps.bump-version.outputs.version != null
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn publish --non-interactive --registry https://registry.npmjs.org/
